Fixed bugs with spellchecker #301
dimkanovikov/KITScenarist pull request #306
Opened 2017-04-28 14:44 UTC by Armijo38

#301 Исправлено

2017-04-28 16:30 UTC, dimkanovikov requested changes
Тут мне кажется ты борщанул :) переводить в нижний регистр надо, при сохранении в словарь или игнорирование, но не на этапе проверки.

2017-04-28 16:30 UTC, dimkanovikov commented on src/bin/scenarist-core/3rd_party/Widgets/SpellCheckTextEdit/SpellCheckTextEdit.cpp
> +            wordWithoutPunctInCorrectRegister = wordWithoutPunct.toLower();
а вот здесь зачем в строчные? это же всегда будет давать ошибку на "Алексей"!? или нет?

2017-04-28 16:30 UTC, dimkanovikov commented on src/bin/scenarist-core/3rd_party/Widgets/SpellCheckTextEdit/SpellCheckTextEdit.cpp
> +            wordWithoutPunctInCorrectRegister = wordWithoutPunct.toLower();
т.е. если кликнуть над Алексеем, то он будет воспринят, как ошибка, мне кажется :)

2017-04-29 09:18 UTC, Armijo38 commented
Исправлено

2017-04-29 10:07 UTC, merged