Impemented locking scene numbers #604
dimkanovikov/KITScenarist pull request #675
Opened 2018-06-01 22:06 UTC by Armijo38

2018-06-02 10:55 UTC, dimkanovikov requested changes

2018-06-02 10:55 UTC, dimkanovikov commented on src/bin/scenarist-desktop/ManagementLayer/Scenario/ScenarioManager.cpp
> +    connect(m_scenario, &ScenarioDocument::fixedScenesChanged, [this] (bool _fixed) {
тут по коннектам с лямбдами новая вводная, правильно их делать не так как мы раньше делали, а задавая контекст (QObject перед лямбдой), чтобы при разрушении контекстного объекта разрушался и конект. Делать это нужно так `connect(EMITTER, SIGNAL, CONTEXT, LAMBDA);` в конкретном этом примере нужно сделать так 
```
connect(m_scenario, &ScenarioDocument::fixedScenesChanged, this, [this] (bool _fixed) {
        m_fixedScenes = _fixed;
        if (!m_workModeIsDraft) {
            m_textEditManager->setFixed(m_fixedScenes);
        }
});
```

2018-06-02 10:55 UTC, dimkanovikov commented on src/bin/scenarist-desktop/ManagementLayer/Scenario/ScenarioManager.cpp
> +        tr("Do you want to unlock or lock?"),
title - Changing scenes numbers locking
text - Do you want to unlock scenes numbers or lock again?

2018-06-02 10:55 UTC, dimkanovikov commented on src/bin/scenarist-desktop/ManagementLayer/Scenario/ScenarioManager.cpp
> +         {QDialogButtonBox::No, tr("Lock")}});
Предлагаю добавить сюда ещё возможность отмены действия кнопкой "я передумала")))

2018-06-02 10:55 UTC, dimkanovikov commented on src/bin/scenarist-desktop/ManagementLayer/Scenario/ScenarioManager.cpp
> +            m_textEditManager->setFixed(m_fixedScenes);
Не нашёл установки этого параметра при переходе от работы со сценарием на черновик и обратно. Кажется оно не будет работать. Т.е. если я зафиксирую номера сцен и перейду к работе с черновиком редактор продолжит находиться в зафиксированном режиме. Или я ошибаюсь?

2018-06-02 10:55 UTC, dimkanovikov commented on src/bin/scenarist-desktop/ManagementLayer/Scenario/ScenarioTextEditManager.h
> +        void lockUnlockRequest();
опять название тут и дальше

2018-06-02 10:55 UTC, dimkanovikov commented on src/bin/scenarist-desktop/ManagementLayer/Scenario/ScenarioTextEditManager.h
> +        void setFixed(bool _fixed);
Не заметил, чтобы при загрузке документов настривалось состояние загруженного документа. Скорей всего иконка просто будет оставаться в последнем состоянии если переключаться между разными документами с зафиксированными номерами сцен и без.

2018-06-03 08:02 UTC, Armijo38 commented on src/bin/scenarist-desktop/ManagementLayer/Scenario/ScenarioManager.cpp
> +            m_textEditManager->setFixed(m_fixedScenes);
Да, верно. Это я пропустил.

2018-06-03 08:04 UTC, Armijo38 commented on src/bin/scenarist-desktop/ManagementLayer/Scenario/ScenarioTextEditManager.h
> +        void setFixed(bool _fixed);
А вот тут ты ошибаешься. ScenarioModel при обновлении номеров сцен испустит сигнал, если изменилось состояние заблокированности. А значит при загрузке документа замок будет нормально меняться.
В теории, оно должно работать и при работе с облаком несколькими пользователями (один зафиксировал и это должно отобразиться у другого), но к сожалению, пока потестить не успел.

2018-06-03 14:29 UTC, dimkanovikov commented on src/bin/scenarist-desktop/ManagementLayer/Scenario/ScenarioTextEditManager.h
> +        void setFixed(bool _fixed);
Очень хорошо раз так, беру назад свои слова.

2018-06-03 14:34 UTC, dimkanovikov requested changes

2018-06-03 14:34 UTC, dimkanovikov commented on src/bin/scenarist-desktop/ManagementLayer/Scenario/ScenarioManager.cpp
> +         {QDialogButtonBox::No, tr("Lock")}});
Тут вижу, что кнопка добавилась, но не вижу её обработки, если нажать отмену, то произойдёт повторное применение блокировки и номера который не были заблокированы заблокируются, а должно не происходить вообще ничего, т.е. если пользователь передумал, то документ остаётся в состоянии в котором был до вызова диалога.

2018-06-05 07:55 UTC, merged